//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Web.Resources.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPMS.Web.Resources.Dashboard.Dashboard", typeof(Dashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add meeting.
        /// </summary>
        public static string AddMeeting {
            get {
                return ResourceManager.GetString("AddMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints.
        /// </summary>
        public static string Complaints {
            get {
                return ResourceManager.GetString("Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Requests.
        /// </summary>
        public static string EmployeeRequests {
            get {
                return ResourceManager.GetString("EmployeeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Clients.
        /// </summary>
        public static string FilterByClient {
            get {
                return ResourceManager.GetString("FilterByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Department.
        /// </summary>
        public static string FilterByDepartment {
            get {
                return ResourceManager.GetString("FilterByDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Employee.
        /// </summary>
        public static string FilterByEmployee {
            get {
                return ResourceManager.GetString("FilterByEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Month.
        /// </summary>
        public static string FilterbyMonth {
            get {
                return ResourceManager.GetString("FilterbyMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Project Progress.
        /// </summary>
        public static string FilterByProjectProgress {
            get {
                return ResourceManager.GetString("FilterByProjectProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Projects.
        /// </summary>
        public static string FilterByProjects {
            get {
                return ResourceManager.GetString("FilterByProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Status.
        /// </summary>
        public static string FilterByStatus {
            get {
                return ResourceManager.GetString("FilterByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make new complaint.
        /// </summary>
        public static string MakeComplaint {
            get {
                return ResourceManager.GetString("MakeComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        public static string Meeting {
            get {
                return ResourceManager.GetString("Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tasks.
        /// </summary>
        public static string MyTasks {
            get {
                return ResourceManager.GetString("MyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        public static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment.
        /// </summary>
        public static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
    }
}
