//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Web.Resources.Inventory.RIF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RIF {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RIF() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPMS.Web.Resources.Inventory.RIF.RIF", typeof(RIF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item Form (RIF).
        /// </summary>
        public static string CreatePageBreadCrumb {
            get {
                return ResourceManager.GetString("CreatePageBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Returned Item Form (RIF).
        /// </summary>
        public static string CreatePageHeading {
            get {
                return ResourceManager.GetString("CreatePageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item Form (RIF) Create.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Returned Item Form (RIF) Form.
        /// </summary>
        public static string CreateRFILink {
            get {
                return ResourceManager.GetString("CreateRFILink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item Form (RIF) View.
        /// </summary>
        public static string DetailsPageBreadCrumb {
            get {
                return ResourceManager.GetString("DetailsPageBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Item Form (RIF).
        /// </summary>
        public static string DetailsPageHeading {
            get {
                return ResourceManager.GetString("DetailsPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details RIF (Returned Item Form).
        /// </summary>
        public static string DetailsPageTitle {
            get {
                return ResourceManager.GetString("DetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item Form (RIF) Edit.
        /// </summary>
        public static string EditPageBreadCrumb {
            get {
                return ResourceManager.GetString("EditPageBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item Form (RIF) Edit.
        /// </summary>
        public static string EditPageHeading {
            get {
                return ResourceManager.GetString("EditPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item Form (RIF).
        /// </summary>
        public static string EditPageTitle {
            get {
                return ResourceManager.GetString("EditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Returned Item Form (RIF).
        /// </summary>
        public static string HistoryPageTitle {
            get {
                return ResourceManager.GetString("HistoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Item Form (RIF) History.
        /// </summary>
        public static string HistoryTableTitle {
            get {
                return ResourceManager.GetString("HistoryTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Manager Name.
        /// </summary>
        public static string InventoryManagerName {
            get {
                return ResourceManager.GetString("InventoryManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item Form (RIF) List.
        /// </summary>
        public static string ListPageBreadCrumb {
            get {
                return ResourceManager.GetString("ListPageBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item Form (RIF) List.
        /// </summary>
        public static string ListPageHeading {
            get {
                return ResourceManager.GetString("ListPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item Form (RIF) List.
        /// </summary>
        public static string ListPageTitle {
            get {
                return ResourceManager.GetString("ListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released Quantity.
        /// </summary>
        public static string ReleasedQuantity {
            get {
                return ResourceManager.GetString("ReleasedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        public static string Requester {
            get {
                return ResourceManager.GetString("Requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester Name.
        /// </summary>
        public static string RequesterName {
            get {
                return ResourceManager.GetString("RequesterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Quantity.
        /// </summary>
        public static string ReturnedQuantity {
            get {
                return ResourceManager.GetString("ReturnedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning Reason.
        /// </summary>
        public static string ReturningReason {
            get {
                return ResourceManager.GetString("ReturningReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning Reason in arabic.
        /// </summary>
        public static string ReturningReasonArabic {
            get {
                return ResourceManager.GetString("ReturningReasonArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item request has been updated..
        /// </summary>
        public static string RFIUpdated {
            get {
                return ResourceManager.GetString("RFIUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item request has been created..
        /// </summary>
        public static string RIFCreated {
            get {
                return ResourceManager.GetString("RIFCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string RIFItem_WarehouseId_Warehouse {
            get {
                return ResourceManager.GetString("RIFItem_WarehouseId_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Item Form (RIF) Number.
        /// </summary>
        public static string RifNo {
            get {
                return ResourceManager.GetString("RifNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIF#.
        /// </summary>
        public static string RIFNumber {
            get {
                return ResourceManager.GetString("RIFNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Returned Item request has been replied..
        /// </summary>
        public static string RIFReplied {
            get {
                return ResourceManager.GetString("RIFReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
    }
}
