//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.WebModels.Resources.WebsiteClient.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPMS.WebModels.Resources.WebsiteClient.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We always provide you the best we can to help you get what you want.
        /// </summary>
        public static string BottomMessage {
            get {
                return ResourceManager.GetString("BottomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Detail.
        /// </summary>
        public static string DepartmentDetail {
            get {
                return ResourceManager.GetString("DepartmentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For More.
        /// </summary>
        public static string ForMore {
            get {
                return ResourceManager.GetString("ForMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Map Location.
        /// </summary>
        public static string GoogleMapLocation {
            get {
                return ResourceManager.GetString("GoogleMapLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Departments.
        /// </summary>
        public static string MainDepartments {
            get {
                return ResourceManager.GetString("MainDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items.
        /// </summary>
        public static string NumberOfItems {
            get {
                return ResourceManager.GetString("NumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Departments.
        /// </summary>
        public static string OurDepartments {
            get {
                return ResourceManager.GetString("OurDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Partners.
        /// </summary>
        public static string OurPartners {
            get {
                return ResourceManager.GetString("OurPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poduct Classification.
        /// </summary>
        public static string PoductClassification {
            get {
                return ResourceManager.GetString("PoductClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASAR Scientific Company.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP.
        /// </summary>
        public static string TOP {
            get {
                return ResourceManager.GetString("TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
