//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantExperience
    {
        public long ExperienceId { get; set; }
        public Nullable<long> ApplicantId { get; set; }
        public string JobTitle { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string CompanyName { get; set; }
        public string TypeOfWork { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string ReasonToLeave { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual JobApplicant JobApplicant { get; set; }
    }
}
