//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.NotificationRecipients = new HashSet<NotificationRecipient>();
            this.RFIs = new HashSet<RFI>();
            this.UserPrefrences = new HashSet<UserPrefrence>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.RIFs = new HashSet<RIF>();
            this.DIFs = new HashSet<DIF>();
            this.DIFManager = new HashSet<DIF>();
            this.POFs = new HashSet<POF>();
            this.POFManager = new HashSet<POF>();
            this.TIRs = new HashSet<TIR>();
            this.TIRManager = new HashSet<TIR>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrderManager = new HashSet<PurchaseOrder>();
            this.DIFHistory = new HashSet<DIFHistory>();
            this.DIFHistoryManager = new HashSet<DIFHistory>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string Address { get; set; }
        public string ImageName { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<NotificationRecipient> NotificationRecipients { get; set; }
        public virtual ICollection<RFI> RFIs { get; set; }
        public virtual ICollection<UserPrefrence> UserPrefrences { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<RIF> RIFs { get; set; }
        public virtual ICollection<DIF> DIFs { get; set; }
        public virtual ICollection<DIF> DIFManager { get; set; }
        public virtual ICollection<POF> POFs { get; set; }
        public virtual ICollection<POF> POFManager { get; set; }
        public virtual ICollection<TIR> TIRs { get; set; }
        public virtual ICollection<TIR> TIRManager { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrderManager { get; set; }
        public virtual ICollection<DIFHistory> DIFHistory { get; set; }
        public virtual ICollection<DIFHistory> DIFHistoryManager { get; set; }
    }
}
