//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public long CompanyId { get; set; }
        public string CompanyNameE { get; set; }
        public string CompanyNameA { get; set; }
        public string CompanyLogoPath { get; set; }
        public string CompanyWebsite { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyAddressE { get; set; }
        public string CompanyAddressA { get; set; }
        public string CompanyLocation { get; set; }
        public string CompanyNumber { get; set; }
        public string CompanyMobileNumber { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<System.DateTime> RecCreatedDate { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public Nullable<System.DateTime> RecLastUpdatedDate { get; set; }
    
        public virtual CompanyBankDetail CompanyBankDetail { get; set; }
        public virtual CompanyDocumentDetail CompanyDocumentDetail { get; set; }
        public virtual CompanySocialDetail CompanySocialDetail { get; set; }
    }
}
