//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Complaints = new HashSet<Complaint>();
            this.JobApplicants = new HashSet<JobApplicant>();
            this.JobTitles = new HashSet<JobTitle>();
        }
    
        public long DepartmentId { get; set; }
        public string DepartmentNameE { get; set; }
        public string DepartmentNameA { get; set; }
        public string DepartmentDesc { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<System.DateTime> RecCreatedDt { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public Nullable<System.DateTime> RecLastUpdatedDt { get; set; }
    
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual ICollection<JobApplicant> JobApplicants { get; set; }
        public virtual ICollection<JobTitle> JobTitles { get; set; }
    }
}
