//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Allowances = new HashSet<Allowance>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.EmployeeJobHistories = new HashSet<EmployeeJobHistory>();
            this.EmployeeRequests = new HashSet<EmployeeRequest>();
            this.MeetingAttendees = new HashSet<MeetingAttendee>();
            this.NotificationRecipients = new HashSet<NotificationRecipient>();
            this.TaskEmployees = new HashSet<TaskEmployee>();
            this.Warehouses = new HashSet<Warehouse>();
        }
    
        public long EmployeeId { get; set; }
        public string EmployeeFirstNameE { get; set; }
        public string EmployeeMiddleNameE { get; set; }
        public string EmployeeLastNameE { get; set; }
        public string EmployeeFirstNameA { get; set; }
        public string EmployeeMiddleNameA { get; set; }
        public string EmployeeLastNameA { get; set; }
        public string EmployeeImagePath { get; set; }
        public Nullable<long> JobTitleId { get; set; }
        public string EmployeeJobId { get; set; }
        public string EmployeeMobileNum { get; set; }
        public string EmployeeLandlineNum { get; set; }
        public Nullable<byte> MaritalStatus { get; set; }
        public Nullable<System.DateTime> EmployeeDOB { get; set; }
        public string EmployeeNationality { get; set; }
        public string EmployeeIqama { get; set; }
        public Nullable<System.DateTime> EmployeeIqamaIssueDt { get; set; }
        public Nullable<System.DateTime> EmployeeIqamaExpiryDt { get; set; }
        public string EmployeePassportNum { get; set; }
        public Nullable<System.DateTime> EmployeePassportExpiryDt { get; set; }
        public string EmployeeDetailsE { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<System.DateTime> RecCreatedDt { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public Nullable<System.DateTime> RecLastUpdatedDt { get; set; }
        public string Email { get; set; }
        public string EmployeeDetailsA { get; set; }
        public Nullable<bool> IsActivated { get; set; }
    
        public virtual ICollection<Allowance> Allowances { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual ICollection<EmployeeJobHistory> EmployeeJobHistories { get; set; }
        public virtual ICollection<EmployeeRequest> EmployeeRequests { get; set; }
        public virtual ICollection<MeetingAttendee> MeetingAttendees { get; set; }
        public virtual ICollection<NotificationRecipient> NotificationRecipients { get; set; }
        public virtual ICollection<TaskEmployee> TaskEmployees { get; set; }
        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}
