//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRequest
    {
        public EmployeeRequest()
        {
            this.RequestDetails = new HashSet<RequestDetail>();
        }
    
        public long RequestId { get; set; }
        public long EmployeeId { get; set; }
        public string RequestTopic { get; set; }
        public System.DateTime RequestDate { get; set; }
        public bool IsMonetary { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<System.DateTime> RecCreatedDt { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public Nullable<System.DateTime> RecLastUpdatedDt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<RequestDetail> RequestDetails { get; set; }
    }
}
