//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemImage
    {
        public long ImageId { get; set; }
        public string ItemImagePath { get; set; }
        public Nullable<int> ImageOrder { get; set; }
        public bool ShowImage { get; set; }
        public long ItemVariationId { get; set; }
    
        public virtual ItemVariation ItemVariation { get; set; }
    }
}
