//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemManufacturer
    {
        public long ItemVariationId { get; set; }
        public long ManufacturerId { get; set; }
        public string Price { get; set; }
    
        public virtual ItemVariation ItemVariation { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
