//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRelease
    {
        public ItemRelease()
        {
            this.ItemReleaseDetails = new HashSet<ItemReleaseDetail>();
        }
    
        public long ItemReleaseId { get; set; }
        public string FormNumber { get; set; }
        public string CreatedBy { get; set; }
        public string ShipmentDetails { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<long> RequesterId { get; set; }
        public Nullable<long> RFIId { get; set; }
        public string OrderNo { get; set; }
        public string DeliveryInfo { get; set; }
        public string DeliveryInfoArabic { get; set; }
        public string RecCreatedBy { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public string RecUpdatedBy { get; set; }
        public System.DateTime RecUpdatedDate { get; set; }
        public long QuantityReleased { get; set; }
        public string Notes { get; set; }
        public string NotesAr { get; set; }
        public string ManagerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RFI RFI { get; set; }
        public virtual ICollection<ItemReleaseDetail> ItemReleaseDetails { get; set; }
    }
}
