//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplicant
    {
        public JobApplicant()
        {
            this.ApplicantExperiences = new HashSet<ApplicantExperience>();
            this.ApplicantQualifications = new HashSet<ApplicantQualification>();
        }
    
        public long ApplicantId { get; set; }
        public long JobOfferedId { get; set; }
        public string ApplicantFirstNameE { get; set; }
        public string ApplicantMiddleNameE { get; set; }
        public string ApplicantFirstNameA { get; set; }
        public string ApplicantMiddleNameA { get; set; }
        public string ApplicantFamilyNameE { get; set; }
        public string ApplicantFamilyNameA { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<byte> ApplicantSex { get; set; }
        public string ApplicantNationality { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<int> NoOfFamilyMembers { get; set; }
        public string LanguagesKnown { get; set; }
        public bool EmployedNow { get; set; }
        public bool GetMonthlyPayment { get; set; }
        public bool GovernmentEmployeeEver { get; set; }
        public string GovernmentAreaWorked { get; set; }
        public bool GovernmentJobOfficial { get; set; }
        public string ReasonOfLeaving { get; set; }
        public Nullable<System.DateTime> JobLeavingDate { get; set; }
        public bool AcceptAgreement { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
    
        public virtual ICollection<ApplicantExperience> ApplicantExperiences { get; set; }
        public virtual ICollection<ApplicantQualification> ApplicantQualifications { get; set; }
        public virtual Department Department { get; set; }
        public virtual JobOffered JobOffered { get; set; }
    }
}
