//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.MeetingAttendees = new HashSet<MeetingAttendee>();
            this.MeetingDocuments = new HashSet<MeetingDocument>();
        }
    
        public long MeetingId { get; set; }
        public string TopicName { get; set; }
        public string TopicNameAr { get; set; }
        public string RelatedProject { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Agenda { get; set; }
        public string AgendaAr { get; set; }
        public string Discussion { get; set; }
        public string DiscussionAr { get; set; }
        public string Decisions { get; set; }
        public string DecisionsAr { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<System.DateTime> RecCreatedDt { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public Nullable<System.DateTime> RecLastUpdatedDt { get; set; }
        public string AttendeeName1 { get; set; }
        public string AttendeeEmail1 { get; set; }
        public string AttendeeName2 { get; set; }
        public string AttendeeEmail2 { get; set; }
        public string AttendeeName3 { get; set; }
        public string AttendeeEmail3 { get; set; }
    
        public virtual ICollection<MeetingAttendee> MeetingAttendees { get; set; }
        public virtual ICollection<MeetingDocument> MeetingDocuments { get; set; }
    }
}
