//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aisle> Aisles { get; set; }
        public virtual DbSet<Allowance> Allowances { get; set; }
        public virtual DbSet<ApplicantExperience> ApplicantExperiences { get; set; }
        public virtual DbSet<ApplicantQualification> ApplicantQualifications { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<CompanyBankDetail> CompanyBankDetails { get; set; }
        public virtual DbSet<CompanyDocumentDetail> CompanyDocumentDetails { get; set; }
        public virtual DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public virtual DbSet<CompanySocialDetail> CompanySocialDetails { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DashboardWidgetPreference> DashboardWidgetPreferences { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeJobHistory> EmployeeJobHistories { get; set; }
        public virtual DbSet<EmployeeRequest> EmployeeRequests { get; set; }
        public virtual DbSet<InventoryDepartment> InventoryDepartments { get; set; }
        public virtual DbSet<InventoryItem> InventoryItems { get; set; }
        public virtual DbSet<ItemImage> ItemImages { get; set; }
        public virtual DbSet<ItemManufacturer> ItemManufacturers { get; set; }
        public virtual DbSet<ItemVariation> ItemVariations { get; set; }
        public virtual DbSet<JobApplicant> JobApplicants { get; set; }
        public virtual DbSet<JobOffered> JobOffereds { get; set; }
        public virtual DbSet<JobTitle> JobTitles { get; set; }
        public virtual DbSet<JobTitleHistory> JobTitleHistories { get; set; }
        public virtual DbSet<LicenseControlPanel> LicenseControlPanels { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<MeetingAttendee> MeetingAttendees { get; set; }
        public virtual DbSet<MeetingDocument> MeetingDocuments { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuRight> MenuRights { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationRecipient> NotificationRecipients { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectDocument> ProjectDocuments { get; set; }
        public virtual DbSet<ProjectTask> ProjectTasks { get; set; }
        public virtual DbSet<QuickLaunchItem> QuickLaunchItems { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<QuotationItemDetail> QuotationItemDetails { get; set; }
        public virtual DbSet<RequestDetail> RequestDetails { get; set; }
        public virtual DbSet<RFI> RFIs { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Shelf> Shelves { get; set; }
        public virtual DbSet<ShelfSection> ShelfSections { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TaskEmployee> TaskEmployees { get; set; }
        public virtual DbSet<UserPrefrence> UserPrefrences { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorItem> VendorItems { get; set; }
        public virtual DbSet<WarehouseDetail> WarehouseDetails { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<RIF> RIFs { get; set; }
        public virtual DbSet<DIF> DIFs { get; set; }
        public virtual DbSet<POF> POFs { get; set; }
        public virtual DbSet<POFItem> POFItems { get; set; }
        public virtual DbSet<ItemRelease> ItemReleases { get; set; }
        public virtual DbSet<ItemReleaseDetail> ItemReleaseDetails { get; set; }
        public virtual DbSet<TIR> TIRs { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<DIFItem> DIFItems { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<RFIItem> RFIItems { get; set; }
        public virtual DbSet<RIFItem> RIFItems { get; set; }
        public virtual DbSet<TIRItem> TIRItems { get; set; }
        public virtual DbSet<DIFHistory> DIFHistories { get; set; }
        public virtual DbSet<DIFItemHistory> DIFItemHistories { get; set; }
        public virtual DbSet<ItemWarehouse> ItemWarehouses { get; set; }
    }
}
