//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationRecipients = new HashSet<NotificationRecipient>();
        }
    
        public long NotificationId { get; set; }
        public string TitleE { get; set; }
        public string TitleA { get; set; }
        public int CategoryId { get; set; }
        public Nullable<long> SubCategoryId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public int AlertBefore { get; set; }
        public int AlertDateType { get; set; }
        public System.DateTime AlertDate { get; set; }
        public bool SystemGenerated { get; set; }
        public Nullable<bool> ForAdmin { get; set; }
        public System.DateTime AlertAppearDate { get; set; }
        public bool IsEmailSent { get; set; }
        public bool IsSMSsent { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<System.DateTime> RecCreatedDate { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public Nullable<System.DateTime> RecLastUpdatedDate { get; set; }
    
        public virtual ICollection<NotificationRecipient> NotificationRecipients { get; set; }
    }
}
