//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Projects = new HashSet<Project>();
            this.RFIs = new HashSet<RFI>();
            this.RIFs = new HashSet<RIF>();
        }
    
        public long OrderId { get; set; }
        public string OrderNo { get; set; }
        public string OrderDescription { get; set; }
        public string OrderNotes { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Attachment { get; set; }
        public long CustomerId { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<System.DateTime> RecCreatedDt { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public Nullable<System.DateTime> RecLastUpdatedDt { get; set; }
        public Nullable<int> OrderStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<RFI> RFIs { get; set; }
        public virtual ICollection<RIF> RIFs { get; set; }
    }
}
