//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTask
    {
        public ProjectTask()
        {
            this.SubTasks = new HashSet<ProjectTask>();
            this.TaskEmployees = new HashSet<TaskEmployee>();
            this.PreRequisitTask = new HashSet<ProjectTask>();
            this.ProjectTasks = new HashSet<ProjectTask>();
        }
    
        public long TaskId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public long ProjectId { get; set; }
        public string TaskNameE { get; set; }
        public string TaskNameA { get; set; }
        public string DescriptionE { get; set; }
        public string DescriptionA { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string TotalWeight { get; set; }
        public string NotesE { get; set; }
        public string NotesA { get; set; }
        public string TaskProgress { get; set; }
        public Nullable<System.DateTime> RecCreatedDt { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<System.DateTime> RecLastUpdatedDt { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public bool IsParent { get; set; }
        public Nullable<long> ParentTask { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<ProjectTask> SubTasks { get; set; }
        public virtual ProjectTask ParentProjectTask { get; set; }
        public virtual ICollection<TaskEmployee> TaskEmployees { get; set; }
        public virtual ICollection<ProjectTask> PreRequisitTask { get; set; }
        public virtual ICollection<ProjectTask> ProjectTasks { get; set; }
    }
}
