//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorItem
    {
        public long ItemId { get; set; }
        public string ItemDetails { get; set; }
        public long VendorId { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
