//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.WebModels.Resources.Website.WebsiteMainPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebsiteMainPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebsiteMainPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPMS.WebModels.Resources.Website.WebsiteMainPage.WebsiteMainPage", typeof(WebsiteMainPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Department.
        /// </summary>
        public static string CreateNewDepartment {
            get {
                return ResourceManager.GetString("CreateNewDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Partner.
        /// </summary>
        public static string CreateNewPartner {
            get {
                return ResourceManager.GetString("CreateNewPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Slider Image.
        /// </summary>
        public static string CreateNewSliderImage {
            get {
                return ResourceManager.GetString("CreateNewSliderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Order.
        /// </summary>
        public static string DepartmentOrder {
            get {
                return ResourceManager.GetString("DepartmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to hide price ?.
        /// </summary>
        public static string HidePriceConfirmation {
            get {
                return ResourceManager.GetString("HidePriceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page Create.
        /// </summary>
        public static string HomePageCreate {
            get {
                return ResourceManager.GetString("HomePageCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Order.
        /// </summary>
        public static string ImageOrder {
            get {
                return ResourceManager.GetString("ImageOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Main Page Create.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Name.
        /// </summary>
        public static string PartnerName {
            get {
                return ResourceManager.GetString("PartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Show/Hide Price..
        /// </summary>
        public static string PriceShowHideError {
            get {
                return ResourceManager.GetString("PriceShowHideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Price has been successfully done..
        /// </summary>
        public static string PriceShowHideSuccess {
            get {
                return ResourceManager.GetString("PriceShowHideSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to show price ?.
        /// </summary>
        public static string ShowPriceConfirmation {
            get {
                return ResourceManager.GetString("ShowPriceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Product Price.
        /// </summary>
        public static string ShowProductPrice {
            get {
                return ResourceManager.GetString("ShowProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Title.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Home Page.
        /// </summary>
        public static string WebsiteHomePage {
            get {
                return ResourceManager.GetString("WebsiteHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Home Page Create.
        /// </summary>
        public static string WebsiteHomePageCreate {
            get {
                return ResourceManager.GetString("WebsiteHomePageCreate", resourceCulture);
            }
        }
    }
}
