//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.WebModels.Resources.Website.ProductSection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductSectionsCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductSectionsCreate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPMS.WebModels.Resources.Website.ProductSection.ProductSectionsCreate", typeof(ProductSectionsCreate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Product Section Addition.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Arabic.
        /// </summary>
        public static string ContentArabic {
            get {
                return ResourceManager.GetString("ContentArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create further Product Section.
        /// </summary>
        public static string LimitReachedMsg {
            get {
                return ResourceManager.GetString("LimitReachedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sections.
        /// </summary>
        public static string ProductSections {
            get {
                return ResourceManager.GetString("ProductSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sections List.
        /// </summary>
        public static string ProductSectionsList {
            get {
                return ResourceManager.GetString("ProductSectionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Name.
        /// </summary>
        public static string SectionName {
            get {
                return ResourceManager.GetString("SectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Name Arabic.
        /// </summary>
        public static string SectionNameArabic {
            get {
                return ResourceManager.GetString("SectionNameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select parent section.
        /// </summary>
        public static string SelectionErrorMsg {
            get {
                return ResourceManager.GetString("SelectionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show to public?.
        /// </summary>
        public static string ShowToPublic {
            get {
                return ResourceManager.GetString("ShowToPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add Product Section in Imported Products from Inventory.
        /// </summary>
        public static string UnableToCreateForImportedSection {
            get {
                return ResourceManager.GetString("UnableToCreateForImportedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Product Section Updation.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
    }
}
