//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Web.Resources.Inventory.PC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PhysicalCount {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PhysicalCount() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPMS.Web.Resources.Inventory.PC.PhysicalCount", typeof(PhysicalCount).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Count View.
        /// </summary>
        public static string CreatePageHeading {
            get {
                return ResourceManager.GetString("CreatePageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Count List.
        /// </summary>
        public static string CreatePageListBreadcrumbs {
            get {
                return ResourceManager.GetString("CreatePageListBreadcrumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Count View.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id.
        /// </summary>
        public static string EmployeeId {
            get {
                return ResourceManager.GetString("EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Barcode.
        /// </summary>
        public static string ItemBarcode {
            get {
                return ResourceManager.GetString("ItemBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name - SKU Descriptoin.
        /// </summary>
        public static string ItemDetails {
            get {
                return ResourceManager.GetString("ItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in Package.
        /// </summary>
        public static string ItemsInPackage {
            get {
                return ResourceManager.GetString("ItemsInPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Items in Wharewhouse.
        /// </summary>
        public static string ItemsInWharewhouse {
            get {
                return ResourceManager.GetString("ItemsInWharewhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes in Arabic.
        /// </summary>
        public static string NotesAr {
            get {
                return ResourceManager.GetString("NotesAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Packages in Wharewhouse.
        /// </summary>
        public static string NumberOfPackages {
            get {
                return ResourceManager.GetString("NumberOfPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Physical Count List.
        /// </summary>
        public static string PageTitleIndex {
            get {
                return ResourceManager.GetString("PageTitleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Count.
        /// </summary>
        public static string PC {
            get {
                return ResourceManager.GetString("PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC#.
        /// </summary>
        public static string PCNo {
            get {
                return ResourceManager.GetString("PCNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items Count.
        /// </summary>
        public static string TotalItemsCount {
            get {
                return ResourceManager.GetString("TotalItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items Count In Warehouse.
        /// </summary>
        public static string TotalItemsCountInWarehouse {
            get {
                return ResourceManager.GetString("TotalItemsCountInWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items in packages.
        /// </summary>
        public static string TotalItemsInPackages {
            get {
                return ResourceManager.GetString("TotalItemsInPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warhouse.
        /// </summary>
        public static string Warhouse {
            get {
                return ResourceManager.GetString("Warhouse", resourceCulture);
            }
        }
    }
}
