//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.WebModels.Resources.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPMS.WebModels.Resources.Reports.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string Createdby {
            get {
                return ResourceManager.GetString("Createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat Project Report.
        /// </summary>
        public static string CreatProjectReport {
            get {
                return ResourceManager.GetString("CreatProjectReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory System Reports.
        /// </summary>
        public static string InventorySystemListPageHeading {
            get {
                return ResourceManager.GetString("InventorySystemListPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory System Reports List.
        /// </summary>
        public static string InventorySystemReportList {
            get {
                return ResourceManager.GetString("InventorySystemReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Report.
        /// </summary>
        public static string ItemsReport {
            get {
                return ResourceManager.GetString("ItemsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Full.
        /// </summary>
        public static string NotFull {
            get {
                return ResourceManager.GetString("NotFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management Reports List.
        /// </summary>
        public static string ProjectManagementReportList {
            get {
                return ResourceManager.GetString("ProjectManagementReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management Reports.
        /// </summary>
        public static string ProjectManagementReportListPageHeading {
            get {
                return ResourceManager.GetString("ProjectManagementReportListPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Report.
        /// </summary>
        public static string ProjectReport {
            get {
                return ResourceManager.GetString("ProjectReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Report.
        /// </summary>
        public static string ProjectReportTab {
            get {
                return ResourceManager.GetString("ProjectReportTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Report.
        /// </summary>
        public static string ProjectsReport {
            get {
                return ResourceManager.GetString("ProjectsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Project Report.
        /// </summary>
        public static string ProjectViewPageTitle {
            get {
                return ResourceManager.GetString("ProjectViewPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string ReportDate {
            get {
                return ResourceManager.GetString("ReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Report.
        /// </summary>
        public static string TasksReport {
            get {
                return ResourceManager.GetString("TasksReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Project Report.
        /// </summary>
        public static string ViewProjectReport {
            get {
                return ResourceManager.GetString("ViewProjectReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Warehouse Report.
        /// </summary>
        public static string ViewWarehouseReport {
            get {
                return ResourceManager.GetString("ViewWarehouseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat Warehouse Report.
        /// </summary>
        public static string WarehouseCreateReport {
            get {
                return ResourceManager.GetString("WarehouseCreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Name.
        /// </summary>
        public static string WarehouseName {
            get {
                return ResourceManager.GetString("WarehouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Report.
        /// </summary>
        public static string WarehouseReport {
            get {
                return ResourceManager.GetString("WarehouseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Report.
        /// </summary>
        public static string WarehouseReportTab {
            get {
                return ResourceManager.GetString("WarehouseReportTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses Report.
        /// </summary>
        public static string WarehousesReport {
            get {
                return ResourceManager.GetString("WarehousesReport", resourceCulture);
            }
        }
    }
}
