//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.Web.Resources.Inventory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InventoryItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InventoryItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPMS.Web.Resources.Inventory.InventoryItem", typeof(InventoryItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AverageCost.
        /// </summary>
        public static string AverageCost {
            get {
                return ResourceManager.GetString("AverageCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Package Price.
        /// </summary>
        public static string AveragePackagePrice {
            get {
                return ResourceManager.GetString("AveragePackagePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Price.
        /// </summary>
        public static string AveragePrice {
            get {
                return ResourceManager.GetString("AveragePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNew.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Inventory Item.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Information.
        /// </summary>
        public static string DeptInfo {
            get {
                return ResourceManager.GetString("DeptInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description for Quotation in Arabic.
        /// </summary>
        public static string DescForQuotationAr {
            get {
                return ResourceManager.GetString("DescForQuotationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description for Quotation.
        /// </summary>
        public static string DescForQuotationEn {
            get {
                return ResourceManager.GetString("DescForQuotationEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in Arabic.
        /// </summary>
        public static string DescriptionAr {
            get {
                return ResourceManager.GetString("DescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous Arabic.
        /// </summary>
        public static string HazardousAr {
            get {
                return ResourceManager.GetString("HazardousAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous.
        /// </summary>
        public static string HazardousEn {
            get {
                return ResourceManager.GetString("HazardousEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Item has been Added..
        /// </summary>
        public static string IsSaved {
            get {
                return ResourceManager.GetString("IsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Item has been Updated..
        /// </summary>
        public static string IsUpdated {
            get {
                return ResourceManager.GetString("IsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemCode.
        /// </summary>
        public static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name Arabic.
        /// </summary>
        public static string ItemNameAr {
            get {
                return ResourceManager.GetString("ItemNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemNameEn {
            get {
                return ResourceManager.GetString("ItemNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Items List.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name cannot exceed 500 characters. .
        /// </summary>
        public static string NameLengthValidation {
            get {
                return ResourceManager.GetString("NameLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name is required..
        /// </summary>
        public static string NameValidation {
            get {
                return ResourceManager.GetString("NameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity On Hand.
        /// </summary>
        public static string QOnHand {
            get {
                return ResourceManager.GetString("QOnHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Sold.
        /// </summary>
        public static string QSold {
            get {
                return ResourceManager.GetString("QSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity In Hand.
        /// </summary>
        public static string QuantityInHand {
            get {
                return ResourceManager.GetString("QuantityInHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity In Package.
        /// </summary>
        public static string QuantityInPackage {
            get {
                return ResourceManager.GetString("QuantityInPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Sold.
        /// </summary>
        public static string QuantitySold {
            get {
                return ResourceManager.GetString("QuantitySold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Point.
        /// </summary>
        public static string ReorderPoint {
            get {
                return ResourceManager.GetString("ReorderPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Variation (SkU) Description.
        /// </summary>
        public static string SkuDesc {
            get {
                return ResourceManager.GetString("SkuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Inventory Item.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Arabic.
        /// </summary>
        public static string UsageAr {
            get {
                return ResourceManager.GetString("UsageAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string UsageEn {
            get {
                return ResourceManager.GetString("UsageEn", resourceCulture);
            }
        }
    }
}
